### ISSUE TITLE
Update Issues Flysky i6

### ISSUE THREAD

**Issue by MikeS20** [ThomHPL/BaseI6_updater#3]
I'd like to know if this update disturbs or changes or damages any other program feature on the Flysky i6 transmitter?  The 10 channel update is great if it does not corrupt any other radio function.
Mike

**Comment by ThomHPL** [comment]
A few years ago, it was working perfectly fine and without any real risk, because the updater is not touching the bootloader of the device. So it's not more dangerous than the official updater, and should always be recoverable in the worst case. (see https://www.youtube.com/watch?v=BITkrXCR0N8)

But I'm not providing any warranty that this will not brick your device, especially since it's been a few years, and the radio probably had a few official updates since. I'm just pretty confident it won't...

About the other features, this kind of mod is actually a bit "dirty", but is normally located in a free range of the memory. I haven't noticed any bug with it during quite a few hours of flight.

Thomas
